/*
 * This source file was generated by the Gradle 'init' task
 */
package xyz.brandonirizarry;

import xyz.brandonirizarry.matrix.Matrix;

public class App {
    public static void main(String[] args) {
        System.out.println(new Matrix(20, 10));
    }
}
