/*
 * This source file was generated by the Gradle 'init' task
 */
package xyz.brandonirizarry;

import xyz.brandonirizarry.game.Game;

public class App {
    public static void main(String[] args) {
        var game = new Game();

        game.start();
    }
}
