/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10/samples
 */

import org.gradle.api.tasks.JavaExec

group = "xyz.brandonirizarry"
version = "0.1"

plugins {
    application
}

repositories {
    mavenCentral()
}

application {
    mainClass.set("$group.jtetris.JTetris")
}

dependencies {
    testImplementation(libs.junit.jupiter)
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}



tasks.named<Test>("test") {
    useJUnitPlatform()
}

// For now, enable assertions.
tasks.withType<JavaExec> {
    enableAssertions = true
}